# Schema for the configuration files of the Download files module.
download_files.settings:
  type: config_object
  label: 'Download files settings'
  mapping:
    media_types:
      type: array
      label: 'Media types'
