<?php

/**
 * @file
 * Primary module hooks for Hello World module.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Target forms to have the promotion options details component
 * open by default.
 */
function hello_world_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $ids = [
    'node_article_edit_form',
    'node_article_form',
  ];
  if (in_array($form_id, $ids)) {
    // Making promotion options open by default.
    $form['options']['#open'] = TRUE;

    // Change access permissions for a field.
    $user = \Drupal::currentUser();
    // $user = \Drupal::service('current_user');
    $form['field_tags']['#access'] = $user->hasPermission('add tags to articles');
  }
}
